apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi-ds
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-ds
  template:
    metadata:
      labels:
        app: fastapi-ds
    spec:
      containers:
      - image: reasg/fastapi-ds:v1.0
        name: fastapi-ds
        env:
        - name: DATABASE_URL
          value: postgresql://admin:password@db:5432/storedb
        ports:
        - containerPort: 5000
